### PR TITLE
[#11] add ktlint

### LINKED ISSUE #11: Add ktlint
https://github.com/pinterest/ktlint

### PR DESCRIPTION
**Pull request by bmarwell**
fixes #11

### CODE REVIEW

**Comment by bmarwell** [comment]
rebased and force-pushed. Do you want to see another PR where I apply the linting rules?

**Comment by sparsick** [comment]
> rebased and force-pushed. Do you want to see another PR where I apply the linting rules?

No, thank you. @georgberky and me have to discuss which kind of rules we want to. But thanks for pushing this topic.

**Comment by bmarwell** [comment]
> No, thank you. @georgberky and me have to discuss which kind of rules we want to. But thanks for pushing this topic.

By creating this PR and offering to create a fix, I was hoping to became part of the discussion. Thanks for the exclusion then, I guess?? 😢

**Comment by georgberky** [comment]
Hi, @bmarwell , thanks for this PR. I'll have a look, also check the Maven Plugin and see what I think about the base ruleset. I do not want to invest too much time into ktlint while the project is still small, but I'll give it a shot.

**Comment by georgberky** [comment]
My current way of thinking is that I do want properly formatted Kotlin code. If ktlint can help us with that better than Editorconfig and without having to put too much time into it. I'd love to use ktlint. The rules they have on their homepage look great already.

**Comment by georgberky** [comment]
@bmarwell, let's give ktlint a shot. Could you please check out if [gantsign/ktlint-maven-plugin](https://github.com/gantsign/ktlint-maven-plugin) works equally well? If possible I don't want to break out of the Maven universe.

I think `ktlint:check` looks like the goal we want to use. Also binding it to the `verify` phase looks ok to me after I've read

> run any checks to verify the package is valid and meets quality criteria

[here](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Lifecycle_Reference).

If you agree, please use the plugin and let `ktlint:check` run in its default phase, `verify`.

**Comment by sparsick** [comment]
superseeded by #65

**Pull request closed without merging**
