### PR TITLE
[#48] exclude reactor projects

### LINKED ISSUE #48: Exclude reactor projects
## Scenario prerequisites

* multi-module reactor project
* dependencies within modules

## Story

As a lazy developer, I do not want to define ${project.version} for reactor artifacts in each pom file again and again.
Instead, I will define all modules and versions in my dependencyManagement of the reactor project's root pom like so:

```xml
<dependencyManagement>
  <dependency>
    <groupId>reactor.group.id</groupId>
    <artifactId>moduleA</artifactId>
    <version>${project.version}</version>
  </dependency>
</dependencyManagement>
```

## Expected behaviour

Those dependencies from the reactor will be left as-is.

## Actual behaviour

This plugin will pick those managed dependencies up and try to downgrade them to the latest version available in the release repository.

### PR DESCRIPTION
**Pull request by bmarwell**
fixes #48

This PR will exclude reactor projects. See description from the issue.

Contents:

* Added mavenSession to read projects
* Updated tests to have a mavenSession
* Verified that in a project with dependencyManagement, no reactor dependency is being updated.

### CODE REVIEW

**Comment by sparsick** [comment]
Build failed because of something with mockk. I have to check it locally if it's reproducable.

**Comment by bmarwell** [comment]
> Build failed because of something with mockk. I have to check it locally if it's reproducable.

I used the SDK from .sdkmanrc which worked fine on MacOS. But I saw serious problems with ANY other JDK and JDK version: Neither OpenJ9 nor any Java 11/17/18/19 JDK would work. 😢

**Comment by sparsick** [comment]
On local Linux it also works. I check the docker image. It uses openjdk 8u233. I will check if we can use another docker image.

**Comment by sparsick** [comment]
With mockk 1.9.3 it works. I will sync the docker image jdk version sdkmanrc and in a separate PR

**Comment by sparsick** [comment]
https://github.com/georgberky/dependency-update-maven-plugin/pull/53/

syncs the version between SDKMAN and DroneCI

**Comment by sparsick** [comment]
@bmarwell I think we should do the version update in a separate PR to go further with this PR

**Comment by bmarwell** [comment]
> @bmarwell I think we should do the version update in a separate PR to go further with this PR

Yes. I will rebase it once https://github.com/georgberky/dependency-update-maven-plugin/pull/55 and another (tbd PR) is merged. Will create it momentarily.

**Comment by bmarwell** [comment]
@sparsick rebased onto https://github.com/georgberky/dependency-update-maven-plugin/pull/57 (because #57 is needed anyway). So it looks like two commits, but it is only one after merging #57.

**Comment by sparsick** [comment]
Thanks for your PR @bmarwell

**Pull request merged**
